In [3]:
import numpy as np
from numpy import diag
from itertools import chain, repeat
from ipyparallel import Client
import os
import sys
import matplotlib as plt
import networkx as nx
from tqdm import trange
from numpy.linalg import norm, inv

max_rounds = 100000
N = 10
eps = 1e-6

In [ ]:
z = [1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
a = 1
for i in range(9):
    if z[i] != z[i+1]:
        a = 0
        break
print(a)

In [ ]:
s = np.random.rand(N)
np.set_printoptions(precision=3)
print(s)

In [ ]:
s = np.random.rand(N)
np.set_printoptions(precision=3)
print(s)

In [ ]:
# def init_opinion(A, N):
#     np.fill_diagonal(A, 1)
#     s = np.zeros([N, N])   
#     rowSum = A.sum(axis=1) 
#     for i in range(len(rowSum)):
#         a = np.random.rand(rowSum[i])
#         b = a / sum(a)
#         num = 0
#         for j in range(N):
#             if A[i][j] == 1:
#                 s[i][j] = b[num]
#                 num += 1
#     return s

In [ ]:
s = np.zeros(10)
a = np.random.rand(10)
np.around(a, 3)
print(type(a))
print(type(s))
aSum = sum(a)
np.around(aSum, 3)
for i in range(10):
    b = a[i] / aSum
    s[i] = b
print(sum(s))
print(s)

In [ ]:
def adjustNorm(N):
    A = np.array(np.random.randint(2, size=(N, N)))
    np.fill_diagonal(A, 0)
    return A

In [ ]:
A = adjustNorm(N)
rowSum = A.sum(axis=1)
for i in range(len(rowSum)):
    a = np.random.rand(rowSum[i])
    b = a/sum(a)*1
print(A)
print(type(b))
print(b)
print(b.sum())

In [ ]:
A = adjustNorm(10)
np.fill_diagonal(A, 1)
s = np.zeros([N, N])
rowSum = A.sum(axis=1) 
for i in range(len(rowSum)):
    a = np.random.rand(rowSum[i])
    b = a / sum(a)
    num = 0
    for j in range(N):
        if A[i][j] == 1:
            s[i][j] = b[num]
            num += 1
print(a)
print(b)
print(s.sum())

In [ ]:
# def row_stocNorm(A, multiplier):
#     np.fill_diagonal(A, 0)
#     rowSums = np.sum(A, 0)
#     A = A + (diag(rowSums) * multiplier)
    
#     s = np.zeros([N, N])   
#     rowSum = A.sum(axis=1) 
#     for i in range(len(rowSum)):
#         a = np.random.rand(rowSum[i])
#         b = a / sum(a)
#         num = 0
#         for j in range(N):
#             if A[i][j] == 1:
#                 s[i][j] = b[num]
#                 num += 1
#     return row_stochastic(A)

In [4]:
import numpy as np
N = 9
Leader = np.zeros((N,N))
print(Leader)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
def adjustNorm(N):
    A = np.array(np.random.randint(2, size=(N, N)))
    np.fill_diagonal(A, 0)
    return A

In [1]:
import networkx as nx
import numpy as np
from numpy import diag
from itertools import chain, repeat
from ipyparallel import Client
import os
import sys
import matplotlib as plt
import networkx as nx
from tqdm import trange
from numpy.linalg import norm, inv
B = [
    [0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0]
]




In [2]:
temp_H = np.sum(B, axis=0)
H = []
for i in temp_H:
    H.append(i)
rest_H = H
print("type(H): ", type(H))
print("rest_H: ", rest_H)
print("H: ", H)

type(H):  <class 'list'>
rest_H:  [1, 1, 3, 0, 3, 4, 1, 0, 0]
H:  [1, 1, 3, 0, 3, 4, 1, 0, 0]


In [3]:
N = 9
V_1 = []
V = []
k = 0
E = []
max_h = np.max(H)
q = np.where(H == np.max(H))[0][0]
rest_H = H
print(max_h)
print(q)
print("type(H): ", type(H))
print("rest_H: ", rest_H)
print("H: ", H)

4
5
type(H):  <class 'list'>
rest_H:  [1, 1, 3, 0, 3, 4, 1, 0, 0]
H:  [1, 1, 3, 0, 3, 4, 1, 0, 0]


In [138]:

max_h = np.max(H)
q = np.where(H == np.max(H))[0][0]
temp_0 = []
temp_1 = []
temp_E = []
rest = []
for p in range(N):
    if B[p][q] == 1:
        temp_0.append(p)
if len(temp_0) == 0:
    temp_0.append(q)
    V.append(temp_0)
    E.append([])
else:
    temp_0.append(q)
    V.append(temp_0)
    for i in V[k]:
        for j in V[k]:
            if B[i][j] == 1:
                temp_E.append((i, j))
    E.append(temp_E)
for p in range(N):
    if B[q][p] == 1 and p in V[k]:
        temp_1.append(p)
temp_1.append(q)
for p in range(N):
    for q in range(len(temp_1)):
        if B[p][q] == 1 and p not in temp_0:
            temp_0.append(q)
V_1.append(temp_1)

rest = []

for j in range(len(H)):
    is_in = 0
    for i in range(len(V[k])):
        if V[k][i] == j:
            is_in = 1
            H[j] = -1
            break;
    if H[j] != -1:
        rest.append(H[j])      
rest_H = rest
k = k + 1

print("H: ", H)
print("rest_H: ", rest_H)
print("V: ", V)
print("E: ", E)
print("V_1: ", V_1)

H:  [-1, -1, -1, -1, -1, -1, -1, -1, -1]
rest_H:  []
V:  [[2, 3, 4, 8, 5], [1, 0], [7, 6]]
E:  [[(2, 4), (2, 5), (3, 5), (4, 2), (4, 5), (8, 5), (5, 2), (5, 4)], [(1, 0), (0, 1)], [(7, 6)]]
V_1:  [[2, 4, 5], [1, 0], [6]]


In [4]:
max_h = np.max(H)
q = np.where(H == np.max(H))[0][0]
print(max_h)
print(q)

4
5


In [5]:
k = k + 1
temp_0 = []
temp_1 = []
temp_E = []
rest = []

for p in range(N):
    if B[p][q] == 1:
        temp_0.append(p)
print(temp_0)
print(q)
print(rest)
print("V", V)

[2, 3, 4, 8]
5
[]
V []


In [113]:
if len(temp_0) == 0:
    temp_0.append(q)
    V.append(temp_0)
    E.append([])
else:
    temp_0.append(q)
    V.append(temp_0)
    for i in V[k]:
        for j in V[k]:
            if B[i][j] == 1:
                temp_E.append((i, j))
    E.append(temp_E)
print(k)
print("V: ", V)
print("E: ", E)
print(rest)

1
V:  [[2, 3, 4, 8, 5], [1, 0]]
E:  [[(2, 4), (2, 5), (3, 5), (4, 2), (4, 5), (8, 5), (5, 2), (5, 4)], [(1, 0), (0, 1)]]
[]


In [114]:
for p in range(N):
    if B[q][p] == 1:
        temp_1.append(p)
temp_1.append(q)
V_1.append(temp_1)

for 
print('temp_1', temp_1)
print('V_1', V_1)
print('rest', rest)

temp_1 [1, 0]
V_1 [[2, 4, 5], [1, 0]]
rest []


In [115]:
print(len(V[k]))
print(len(H))

2
9


In [116]:
for j in range(len(H)):
    is_in = 0
    for i in range(len(V[k])):
        if V[k][i] == j:
            is_in = 1
            H[j] = -1
            break;
    if H[j] != -1:
        rest.append(H[j])  

print("H: ", H)
print("rest: ", rest)
print("V: ", V)
print("E: ", E)

H:  [-1, -1, -1, -1, -1, -1, 1, 0, -1]
rest:  [1, 0]
V:  [[2, 3, 4, 8, 5], [1, 0]]
E:  [[(2, 4), (2, 5), (3, 5), (4, 2), (4, 5), (8, 5), (5, 2), (5, 4)], [(1, 0), (0, 1)]]


In [117]:
i = 2
while(i):
    print(i)
    i = i -1

2
1


In [ ]:
temp_0 = []
temp_1 = []
V = []

for k in range(len(candidate_1)):
    temp = []
    temp = candidate_1[k]
    for i in range(len(temp)):
        for j in range(len(candidate_0)):
            if B[candidate_0[j]][temp[i]] == 1 and candidate_0[j] not in temp_0:
                temp_0.append(candidate_0[j])
                temp.append(candidate_0[j])
    V.append(temp)
