In [4]:
import numpy as np
from numpy import diag
from itertools import chain, repeat
from ipyparallel import Client
import os
import sys
import matplotlib as plt
import networkx as nx
from tqdm import trange
from numpy.linalg import norm, inv

In [5]:
def adjustNorm(N):
    B = np.array(np.random.randint(2, size=(N, N)))
    np.fill_diagonal(B, 0)
    return B

In [21]:
N = 5
B = adjustNorm(N)
print(B)

[[0 0 0 1 1]
 [1 0 0 1 1]
 [0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]]


In [22]:
temp_H = np.sum(B, axis=0)
H = []
for i in temp_H:
    H.append(i)
rest_H = H
print("type(H): ", type(H))
print("rest_H: ", rest_H)
print("H: ", H)

type(H):  <class 'list'>
rest_H:  [1, 0, 1, 2, 3]
H:  [1, 0, 1, 2, 3]


In [23]:
V_1 = []
V = []
k = 0
E = []
max_h = np.max(H)
q = np.where(H == np.max(H))[0][0]
rest_H = H
print(max_h)
print(q)
print("type(H): ", type(H))
print("rest_H: ", rest_H)
print("H: ", H)    
print(np.where(H == np.max(H))[0][0])

3
4
type(H):  <class 'list'>
rest_H:  [1, 0, 1, 2, 3]
H:  [1, 0, 1, 2, 3]
4


In [24]:
for p in range(N):
    print(p)
    if B[p][q] == 1:
        temp_0.append(p)
print(temp_0)

0
1
2
3
4
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 0, 1, 3]


In [28]:
while(len(rest_H)):
    max_h = np.max(H)
    q = np.where(H == np.max(H))[0][0]
    temp_0 = []
    temp_1 = []
    temp_E = []
    rest = []
    for p in range(N):
        if B[p][q] == 1:
            temp_0.append(p)
    if len(temp_0) == 0:
        temp_0.append(q)
        V.append(temp_0)
        E.append([])
    else:
        temp_0.append(q)
        V.append(temp_0)
        for i in V[k]:
            for j in V[k]:
                if B[i][j] == 1:
                    temp_E.append((i, j))
        E.append(temp_E)
    for p in range(N):
        if B[q][p] == 1 and p in V[k]:
            temp_1.append(p)
    temp_1.append(q)
    V_1.append(temp_1)

    rest = []

    for j in range(len(H)):
        is_in = 0
        for i in range(len(V[k])):
            if V[k][i] == j:
                is_in = 1
                H[j] = -1
                break;
        if H[j] != -1:
            rest.append(H[j])      
    rest_H = rest
    k = k + 1

print("H: ", H)
print("rest_H: ", rest_H)
print("V: ", V)
print("E: ", E)
print("V_1: ", V_1)

H:  [-1, -1, -1, -1, -1]
rest_H:  []
V:  [[0, 1, 3, 4], [4, 2]]
E:  [[(0, 3), (0, 4), (1, 0), (1, 3), (1, 4), (3, 4)], [(4, 2)]]
V_1:  [[4], [2]]
